spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
server:
  port: 8079